### ISSUE TITLE
Default import directory

### ISSUE THREAD

**Issue by oscarotero** [hironichu/denosass#1]
Hi.
Thanks for this awesome project. I was looking forward to using Sass in Deno and, after trying several options, this is the one that works best so far.
My request is related to how the path of imported files is resolved. AFAIK the imports are resolved using the cwd. I'd love to have a way to define the input as a string and configure a file name, in order to use relative imports. And also a way to change the cwd so other non-relative imports are resolved from a different cwd.

Example of how the API could be:

```ts
import sass from "https://deno.land/x/denosass/mod.ts";

const code = `
@import "./styles-1.scss"; /* Relative import */
@import "styles-2.scss"; /* Import from default path */
`;

const options = {
    file: "/projects/web/styles/input.scss",
    cwd: "/projects/web"
};

const compiler = sass(code, options);
```

- The first import is relative to the input file (`/projects/web/styles/input.scss`) so it would be resolved to `/projects/web/styles/styles-1.scss`.
- The second import uses the cwd (`/projects/web`) so it would be resolved to `/projects/web/styles-2.scss`.

Is this possible?

Thanks you!

**Comment by oscarotero** [comment]
Yes, that's exactly what I want. Thank you so much for the quick reply!

FYI, I'm working on a Sass plugin for Lume (a static site generator for Deno I've made), this is the current code:
https://github.com/lumeland/experimental-plugins/blob/main/sass/sass.ts

**Comment by hironichu** [comment]
Oh I have heard about Fume ! I was just thinking about adding a plugin with my module haha !

Well the changes are ready, but I will add some more test cases and once ready to go i will merge !

**Comment by oscarotero** [comment]
Thank you for updating this.
The lume plugin works great: https://github.com/lumeland/experimental-plugins/blob/main/sass/sass.ts

**Comment by hironichu** [comment]
Im gonna need to use Lume really soon, so I look forward to make good use of this plugin ! if there is anything you need to report, feel free to share
