### ISSUE TITLE
Compiling Folders is not working as I expected.

### ISSUE THREAD

**Issue by hacknlove** [hironichu/denosass#11]
I would love to make a PR to "fix" this, but maybe what I am expecting it's not what you want for the API.

1. it is not importing from subfolders

You have explicitly set max Depth to 1 for the walkSync, so maybe you won't like a PR that removes it.

In that case would you be open to accept a parameter to set a different depth?
```js
sass([folder, ...], { maxDepth: n })
```
2. files with the same name are overriding each other

You have a Map to make sure you are only compiling one file with the same name.

I think this behavior can be problematic, and there are tradeoffs with any alternative.

I don't feel confortable making a PR with a decision taken on my own. 

3. it's not appending files (PermissionDenied)

I would workaround  it by creating the string on memory and writing to the disk only once. But maybe you know how to fix it properly.

**Comment by hironichu** [comment]
If you have a working PR by all means go for it, however I have plans to rework this with something more.. stable and reliable but I don't have time anymore.

feel free to make a PR if you think you can add usefull feature or fixes, i'll review it on a weekend

**Comment by hironichu** [comment]
Since these PR have been merged #13 #12 if there isn't anything else we can close this issue !
