### ISSUE TITLE
compiler error caused by rgb

### ISSUE THREAD

**Issue by jiawei397** [hironichu/denosass#15]
Thank you for this project. I am planning to use it.
When I used it to convert the sass files of my old project, an error was reported and the reason was found. It was only caused by the rgb function.
This is an example:
```ts
import sass from "https://deno.land/x/denosass@1.0.6/mod.ts";
const compiler = sass(`
box-shadow: 0 6px 30px 0 rgb(123 129 136 / 25%);
`);
console.log(compiler.to_string());
```
The error is:
```
error: Uncaught "Error: $blue: 5.44%^-1 is not a number.\n  ╷\n2 │ box-shadow: 0 6px 30px 0 rgb(123 129 136 / 25%);\n  │                              ^\n  ╵\n./stdin:2:30\n"
```
It can be fixed by change `25%` to `0.25`. 
But it works well on dart sass.
I wonder if you intend to repair it?

**Comment by hironichu** [comment]
I don't have the hand on the whole Sass / Css Processing, most if is done here https://github.com/connorskees/grass

Closing this, please open an issue there about this problem.
