### ISSUE TITLE
`@use` directive should compute namespace automatically

### ISSUE THREAD

**Issue by binyamin** [hironichu/denosass#6]
I don't know much about WASM, so this may just be an issue of updating the `src/wasm/grass.wasm` file to the latest version of sass.

Either way, I really appreciate all the work you've done. What's the basic architecture here? Maybe I could help with this issue.

**Comment by hironichu** [comment]
The module is based off [Grass ](https://github.com/connorskees/grass) which is not perfect and lack some features,

however the @use syntax should work I believe? what's the real issue you're having ?

Also thank you ! the module is basically just a slightly modified version of the crate I mentioned compiled into Wasm

**Comment by binyamin** [comment]
I'll be honest, I opened the issue based on the readme, without actually testing it. However, I _did_ notice that I need to write `@use '../theme' as theme`. If I omit "as theme", it complains that it can't find the namespace. I'm using lume.

**Comment by hironichu** [comment]
ahh um that is probably an issue of the original module, not sure, I think i will revisit the code since it's been quite some time that i have made an update, thanks for letting me know ! Will update this issue if i find anything new/ or not, if you have anything else make sure to follow up as well!

**Comment by binyamin** [comment]
By the way, I saw some code which seems to be creating a WASM binary straight from the latest dart-sass release. See https://github.com/thedodd/trunk/blob/master/src/tools.rs

**Comment by hironichu** [comment]
There is nothing I can do about this since I'm not the creator of the crate like I mentioned.. it's [Grass](https://github.com/connorskees/grass) , please open a Issue there and I will update the module if such a fix is made throughout the main crate.

**Comment by binyamin** [comment]
@hironichu What do you think about making a WASM build from dart-sass itself? See https://github.com/hironichu/denosass/issues/6#issuecomment-1152523302

**Comment by hironichu** [comment]
It is not currently possible to compile Dart-sass to WASM See https://github.com/dart-lang/sdk/issues/32894

Also, and it's more of a personal choice, I prefer the use of Rust instead of other language that I do not know!
