### ISSUE TITLE
Hangs when imported in a worker

### ISSUE THREAD

**Issue by Blocksnmore** [hironichu/denosass#9]
For some reason denosass (using 1.0.4) hangs the worker it got imported within. I'm importing it like this:
```
import scss from "https://deno.land/x/denosass@1.0.4/mod.ts";
```
Deno info:
```
deno 1.25.0 (release, x86_64-unknown-linux-gnu)
v8 10.6.194.5
typescript 4.7.4
```

**Comment by hironichu** [comment]
I tried to run as you said, It "hangs" because you have a worker running, not because of my module

In the worker you can use self.close() when you're done. In the main process you can call the variable on which you have assigned the worker and call the terminate() method.

```ts

const worker = new Worker(...)
worker.terminate();

```

**Comment by Blocksnmore** [comment]
I have no clue why but it seems to be working now (I didn't change anything in my code)
